### ISSUE TITLE
Add ITA 2025 Physics essay exam

### ISSUE THREAD

**Issue by lgabs** [lgabs/gpt-resolve#3]
The Physics exam should follow a similar approach to the ITA math essay exam. Each question should be captured as a screenshot and saved appropriately in the `exams` folder for processing by `resolve.py`.

It may be somewhat challenging for GPT-4 to accurately describe the images for o1-preview, and this will factor into the performance evaluation we'll be conducting.

You can find the essay questions here:  
[https://vestibular.ita.br/](https://vestibular.ita.br/)

Tasks:
- [x] Add each exam question as a screenshot.
- [x] Solve the questions using `gpt-resolve`, generating solution files in LaTeX syntax.
- [x] Automatically compile a PDF of solutions using `gpt-resolve`.
- [x] Add documentaion for this exam

**Comment by joaoduarteN** [comment]
I'll work on this one

**Comment by lgabs** [comment]
Hi @joaoduarteN , thanks for your interest in the project! I only saw your comment today, and yesterday morning I began solving the questions locally and started reviewing them. Physics is a bit more challenging to review, and I’m halfway through.

It’s awesome that you already opened PR #13 to add screenshots—thanks for that! I’ll merge it today.

After that, the issue will be complete once we finish reviewing the o1-preview solutions. I’ll aim to complete this by next Saturday, but I’ll open a draft PR in the meantime so you can see the progress too. It would be great to have your review on them if you're available!
